// src/pages/UserManagement.tsx
import { useState, useEffect } from 'react'
import { AlertTriangle, Loader2, Plus, Search, Edit, Key, UserX, UserCheck, X } from 'lucide-react'
import { systemApi } from '../api/modules/system.api'
import type { User, UserStatus, Department } from '../types'
import type { CreateUserRequest, UpdateUserRequest } from '../api/modules/system.api'

interface UserFormData {
  username: string
  password: string
  name: string
  email: string
  phone: string
  departmentId: string
  roleIds: string[]
}

export function UserManagement() {
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [users, setUsers] = useState<User[]>([])
  const [pagination, setPagination] = useState({
    total: 0,
    page: 1,
    pageSize: 20,
    totalPages: 0,
  })
  
  // Filter state
  const [keyword, setKeyword] = useState('')
  const [statusFilter, setStatusFilter] = useState<UserStatus | ''>('')
  
  // Modal state
  const [showModal, setShowModal] = useState(false)
  const [modalMode, setModalMode] = useState<'create' | 'edit'>('create')
  const [selectedUser, setSelectedUser] = useState<User | null>(null)
  const [saving, setSaving] = useState(false)
  
  // Form data
  const [formData, setFormData] = useState<UserFormData>({
    username: '',
    password: '',
    name: '',
    email: '',
    phone: '',
    departmentId: '',
    roleIds: [],
  })
  
  // Available options
  const [departments, setDepartments] = useState<Department[]>([])
  const [availableRoles, setAvailableRoles] = useState<{ id: string; displayName: string }[]>([])

  const fetchUsers = async (page = 1) => {
    try {
      setLoading(true)
      setError(null)
      
      const response = await systemApi.getUsers({
        page,
        pageSize: pagination.pageSize,
        keyword: keyword || undefined,
        status: statusFilter || undefined,
      })
      
      setUsers(response.data.items)
      setPagination({
        total: response.data.total,
        page: response.data.page,
        pageSize: response.data.pageSize,
        totalPages: response.data.totalPages,
      })
    } catch (err: any) {
      console.error('Failed to fetch users:', err)
      setError(err.response?.data?.message || '获取用户列表失败')
    } finally {
      setLoading(false)
    }
  }

  const fetchOptions = async () => {
    try {
      // Fetch departments and roles
      const [rolesRes] = await Promise.all([
        systemApi.getRoles(),
        // Could add department API call here if available
      ])
      
      setAvailableRoles(rolesRes.data.map(r => ({ id: r.id, displayName: r.displayName })))
    } catch (err: any) {
      console.error('Failed to fetch options:', err)
    }
  }

  useEffect(() => {
    fetchUsers(1)
    fetchOptions()
  }, [])

  const handleSearch = () => {
    fetchUsers(1)
  }

  const handleOpenCreate = () => {
    setModalMode('create')
    setSelectedUser(null)
    setFormData({
      username: '',
      password: '',
      name: '',
      email: '',
      phone: '',
      departmentId: '',
      roleIds: [],
    })
    setShowModal(true)
  }

  const handleOpenEdit = (user: User) => {
    setModalMode('edit')
    setSelectedUser(user)
    setFormData({
      username: user.username,
      password: '',
      name: user.name,
      email: user.email || '',
      phone: user.phone || '',
      departmentId: user.departmentId,
      roleIds: user.roles?.map(r => r.roleId) || [],
    })
    setShowModal(true)
  }

  const handleSave = async () => {
    try {
      setSaving(true)
      
      if (modalMode === 'create') {
        if (!formData.username || !formData.password || !formData.name || !formData.departmentId) {
          setError('请填写必填项')
          return
        }
        
        await systemApi.createUser(formData as CreateUserRequest)
      } else if (selectedUser) {
        const updateData: UpdateUserRequest = {
          name: formData.name,
          email: formData.email,
          phone: formData.phone,
          departmentId: formData.departmentId,
          roleIds: formData.roleIds,
        }
        
        await systemApi.updateUser(selectedUser.id, updateData)
      }
      
      setShowModal(false)
      fetchUsers(pagination.page)
    } catch (err: any) {
      console.error('Save failed:', err)
      setError(err.response?.data?.message || '保存失败')
    } finally {
      setSaving(false)
    }
  }

  const handleToggleStatus = async (user: User) => {
    try {
      const newStatus = user.status === 'ACTIVE' ? 'DISABLED' : 'ACTIVE'
      await systemApi.updateUser(user.id, { status: newStatus as UserStatus })
      fetchUsers(pagination.page)
    } catch (err: any) {
      console.error('Toggle status failed:', err)
      setError(err.response?.data?.message || '操作失败')
    }
  }

  const handleResetPassword = async (user: User) => {
    const newPassword = prompt(`请输入 ${user.name} 的新密码：`)
    if (!newPassword) return
    
    try {
      await systemApi.resetPassword(user.id, { newPassword })
      alert('密码重置成功')
    } catch (err: any) {
      console.error('Reset password failed:', err)
      setError(err.response?.data?.message || '密码重置失败')
    }
  }

  const getStatusTag = (status: UserStatus) => {
    const statusConfig: Record<UserStatus, { label: string; className: string }> = {
      ACTIVE: { label: '启用', className: 'tag-success' },
      DISABLED: { label: '禁用', className: 'tag-danger' },
      LOCKED: { label: '锁定', className: 'tag-warning' },
    }
    return statusConfig[status] || { label: status, className: 'tag-default' }
  }

  return (
    <div className="user-management-page">
      <div className="page-header">
        <div>
          <h1 className="page-title">用户管理</h1>
          <p className="page-subtitle">管理系统用户账户</p>
        </div>
        <button className="btn btn-primary" onClick={handleOpenCreate}>
          <Plus size={16} /> 新建用户
        </button>
      </div>

      {error && (
        <div className="alert alert-error">
          <AlertTriangle size={16} /> {error}
        </div>
      )}

      {/* Filters */}
      <div className="card">
        <div className="filters-row">
          <div className="input-group">
            <input
              type="text"
              className="input"
              placeholder="搜索用户名或姓名"
              value={keyword}
              onChange={(e) => setKeyword(e.target.value)}
              onKeyDown={(e) => e.key === 'Enter' && handleSearch()}
            />
          </div>
          <select
            className="select"
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value as UserStatus | '')}
          >
            <option value="">全部状态</option>
            <option value="ACTIVE">启用</option>
            <option value="DISABLED">禁用</option>
            <option value="LOCKED">锁定</option>
          </select>
          <button className="btn btn-primary" onClick={handleSearch}>
            <Search size={16} /> 搜索
          </button>
        </div>
      </div>

      {/* Users Table */}
      <div className="card mt-4">
        {loading ? (
          <div className="loading-container">
            <Loader2 className="spinner" size={32} />
            <p>加载中...</p>
          </div>
        ) : users.length === 0 ? (
          <div className="empty-state">暂无用户数据</div>
        ) : (
          <table className="table">
            <thead>
              <tr>
                <th>用户名</th>
                <th>姓名</th>
                <th>部门</th>
                <th>角色</th>
                <th>状态</th>
                <th>最后登录</th>
                <th>操作</th>
              </tr>
            </thead>
            <tbody>
              {users.map((user) => {
                const status = getStatusTag(user.status)
                return (
                  <tr key={user.id}>
                    <td className="font-medium">{user.username}</td>
                    <td>{user.name}</td>
                    <td>{user.department?.name || '-'}</td>
                    <td>
                      {user.roles?.map((ur, index) => (
                        <span key={index} className="tag tag-info">{ur.role?.displayName || ur.roleId}</span>
                      ))}
                    </td>
                    <td>
                      <span className={`tag ${status.className}`}>{status.label}</span>
                    </td>
                    <td>{user.lastLoginAt ? new Date(user.lastLoginAt).toLocaleString() : '-'}</td>
                    <td>
                      <div className="action-buttons">
                        <button 
                          className="btn btn-secondary btn-sm"
                          onClick={() => handleOpenEdit(user)}
                          title="编辑"
                        >
                          <Edit size={14} />
                        </button>
                        <button 
                          className="btn btn-secondary btn-sm"
                          onClick={() => handleResetPassword(user)}
                          title="重置密码"
                        >
                          <Key size={14} />
                        </button>
                        <button 
                          className={`btn btn-sm ${user.status === 'ACTIVE' ? 'btn-danger' : 'btn-success'}`}
                          onClick={() => handleToggleStatus(user)}
                          title={user.status === 'ACTIVE' ? '禁用' : '启用'}
                        >
                          {user.status === 'ACTIVE' ? <UserX size={14} /> : <UserCheck size={14} />}
                        </button>
                      </div>
                    </td>
                  </tr>
                )
              })}
            </tbody>
          </table>
        )}

        {/* Pagination */}
        {pagination.totalPages > 1 && (
          <div className="pagination">
            <button 
              className="btn btn-secondary"
              disabled={pagination.page <= 1}
              onClick={() => fetchUsers(pagination.page - 1)}
            >
              上一页
            </button>
            <span className="page-info">
              第 {pagination.page} / {pagination.totalPages} 页
            </span>
            <button 
              className="btn btn-secondary"
              disabled={pagination.page >= pagination.totalPages}
              onClick={() => fetchUsers(pagination.page + 1)}
            >
              下一页
            </button>
          </div>
        )}
      </div>

      {/* User Modal */}
      {showModal && (
        <div className="modal-overlay" onClick={() => setShowModal(false)}>
          <div className="modal" onClick={e => e.stopPropagation()}>
            <div className="modal-header">
              <h3 className="modal-title">
                {modalMode === 'create' ? '新建用户' : '编辑用户'}
              </h3>
              <button className="modal-close" onClick={() => setShowModal(false)}>
                <X size={20} />
              </button>
            </div>
            <div className="modal-body">
              <div className="form-grid">
                <div className="input-group">
                  <label className="input-label">用户名 *</label>
                  <input
                    type="text"
                    className="input"
                    value={formData.username}
                    onChange={(e) => setFormData({ ...formData, username: e.target.value })}
                    disabled={modalMode === 'edit'}
                    placeholder="请输入用户名"
                  />
                </div>
                {modalMode === 'create' && (
                  <div className="input-group">
                    <label className="input-label">密码 *</label>
                    <input
                      type="password"
                      className="input"
                      value={formData.password}
                      onChange={(e) => setFormData({ ...formData, password: e.target.value })}
                      placeholder="请输入密码"
                    />
                  </div>
                )}
                <div className="input-group">
                  <label className="input-label">姓名 *</label>
                  <input
                    type="text"
                    className="input"
                    value={formData.name}
                    onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                    placeholder="请输入姓名"
                  />
                </div>
                <div className="input-group">
                  <label className="input-label">邮箱</label>
                  <input
                    type="email"
                    className="input"
                    value={formData.email}
                    onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                    placeholder="请输入邮箱"
                  />
                </div>
                <div className="input-group">
                  <label className="input-label">手机</label>
                  <input
                    type="tel"
                    className="input"
                    value={formData.phone}
                    onChange={(e) => setFormData({ ...formData, phone: e.target.value })}
                    placeholder="请输入手机号"
                  />
                </div>
                <div className="input-group">
                  <label className="input-label">部门 *</label>
                  <select
                    className="select"
                    value={formData.departmentId}
                    onChange={(e) => setFormData({ ...formData, departmentId: e.target.value })}
                  >
                    <option value="">请选择部门</option>
                    {departments.map((dept) => (
                      <option key={dept.id} value={dept.id}>{dept.name}</option>
                    ))}
                  </select>
                </div>
                <div className="input-group full-width">
                  <label className="input-label">角色</label>
                  <div className="checkbox-group">
                    {availableRoles.map((role) => (
                      <label key={role.id} className="checkbox-label">
                        <input
                          type="checkbox"
                          checked={formData.roleIds.includes(role.id)}
                          onChange={(e) => {
                            if (e.target.checked) {
                              setFormData({ ...formData, roleIds: [...formData.roleIds, role.id] })
                            } else {
                              setFormData({ ...formData, roleIds: formData.roleIds.filter(id => id !== role.id) })
                            }
                          }}
                        />
                        {role.displayName}
                      </label>
                    ))}
                  </div>
                </div>
              </div>
            </div>
            <div className="modal-footer">
              <button className="btn btn-secondary" onClick={() => setShowModal(false)}>取消</button>
              <button 
                className="btn btn-primary" 
                onClick={handleSave}
                disabled={saving}
              >
                {saving ? '保存中...' : '保存'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

// frontend/src/pages/UserManagement.vue
<template>
  <div class="page-container">
    <!-- 顶部工具栏 -->
    <div class="toolbar">
      <div class="toolbar-left">
        <el-input
          v-model="searchQuery"
          placeholder="搜索用户名/姓名"
          clearable
          style="width: 200px"
          @keyup.enter="handleSearch"
        >
          <template #prefix>
            <el-icon><Search /></el-icon>
          </template>
        </el-input>
        <el-tree-select
          v-model="filterDepartmentId"
          :data="departmentTree"
          placeholder="选择部门"
          clearable
          :props="{ label: 'name', value: 'id' } as any"
          style="width: 200px"
          @change="handleSearch"
        />
        <el-select v-model="filterStatus" placeholder="状态筛选" clearable style="width: 120px" @change="handleSearch">
          <el-option label="启用" value="ACTIVE" />
          <el-option label="禁用" value="INACTIVE" />
          <el-option label="锁定" value="LOCKED" />
        </el-select>
        <el-button type="primary" @click="handleSearch">
          <el-icon><Search /></el-icon>搜索
        </el-button>
        <el-button @click="handleReset">重置</el-button>
      </div>
      <div class="toolbar-right">
        <el-button type="primary" @click="handleAdd">
          <el-icon><Plus /></el-icon>新增用户
        </el-button>
      </div>
    </div>

    <!-- 数据表格 -->
    <el-table v-loading="loading" :data="userList" border stripe style="margin-top: 16px">
      <el-table-column prop="username" label="用户名" min-width="120" />
      <el-table-column prop="realName" label="姓名" min-width="100" />
      <el-table-column prop="email" label="邮箱" min-width="180" />
      <el-table-column prop="phone" label="手机" min-width="120" />
      <el-table-column label="部门" min-width="150">
        <template #default="{ row }">
          {{ row.department?.name || '-' }}
        </template>
      </el-table-column>
      <el-table-column label="角色" min-width="200">
        <template #default="{ row }">
          <el-tag v-for="role in row.roles" :key="role.id" size="small" style="margin-right: 4px; margin-bottom: 4px">
            {{ (ROLE_LABELS as Record<string, string>)[role.code] || role.name }}
          </el-tag>
        </template>
      </el-table-column>
      <el-table-column label="状态" width="100">
        <template #default="{ row }">
          <el-tag :type="getStatusType(row.status) as any" size="small">
            {{ getStatusLabel(row.status) }}
          </el-tag>
        </template>
      </el-table-column>
      <el-table-column label="最后登录" min-width="160">
        <template #default="{ row }">
          {{ row.lastLoginAt ? formatDateTime(row.lastLoginAt) : '-' }}
        </template>
      </el-table-column>
      <el-table-column label="操作" width="200" fixed="right">
        <template #default="{ row }">
          <el-button type="primary" link size="small" @click="handleEdit(row)">编辑</el-button>
          <el-button type="primary" link size="small" @click="handleResetPassword(row)">重置密码</el-button>
          <el-button
            :type="row.status === 'ACTIVE' ? 'danger' : 'success'"
            link
            size="small"
            @click="handleToggleStatus(row)"
          >
            {{ row.status === 'ACTIVE' ? '禁用' : '启用' }}
          </el-button>
        </template>
      </el-table-column>
    </el-table>

    <!-- 分页 -->
    <div class="pagination-container">
      <el-pagination
        v-model:current-page="pagination.page"
        v-model:page-size="pagination.pageSize"
        :page-sizes="[10, 20, 50, 100]"
        :total="pagination.total"
        layout="total, sizes, prev, pager, next, jumper"
        @size-change="handleSizeChange"
        @current-change="handlePageChange"
      />
    </div>

    <!-- 新增/编辑用户弹窗 -->
    <el-dialog
      v-model="dialogVisible"
      :title="isEdit ? '编辑用户' : '新增用户'"
      width="600px"
      destroy-on-close
    >
      <el-form ref="formRef" :model="formData" :rules="formRules" label-width="100px">
        <el-form-item label="用户名" prop="username">
          <el-input v-model="formData.username" :disabled="isEdit" placeholder="请输入用户名" />
        </el-form-item>
        <el-form-item label="姓名" prop="realName">
          <el-input v-model="formData.realName" placeholder="请输入姓名" />
        </el-form-item>
        <el-form-item label="密码" prop="password" v-if="!isEdit">
          <el-input v-model="formData.password" type="password" show-password placeholder="请输入密码" />
        </el-form-item>
        <el-form-item label="邮箱" prop="email">
          <el-input v-model="formData.email" placeholder="请输入邮箱" />
        </el-form-item>
        <el-form-item label="手机" prop="phone">
          <el-input v-model="formData.phone" placeholder="请输入手机号" />
        </el-form-item>
        <el-form-item label="部门" prop="departmentId">
          <el-tree-select
            v-model="formData.departmentId"
            :data="departmentTree"
            placeholder="选择部门"
            clearable
            :props="{ label: 'name', value: 'id' } as any"
            style="width: 100%"
          />
        </el-form-item>
        <el-form-item label="角色" prop="roleIds">
          <el-select v-model="formData.roleIds" multiple placeholder="选择角色" style="width: 100%">
            <el-option
              v-for="role in roleList"
              :key="role.id"
              :label="(ROLE_LABELS as Record<string, string>)[role.code] || role.name"
              :value="role.id"
            />
          </el-select>
        </el-form-item>
        <el-form-item label="状态" prop="status">
          <el-radio-group v-model="formData.status">
            <el-radio label="ACTIVE">启用</el-radio>
            <el-radio label="INACTIVE">禁用</el-radio>
          </el-radio-group>
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="dialogVisible = false">取消</el-button>
        <el-button type="primary" :loading="submitLoading" @click="handleSubmit">确定</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Search, Plus } from '@element-plus/icons-vue'
import type { FormInstance, FormRules } from 'element-plus'
import * as userApi from '@/api/modules/user'
import * as departmentApi from '@/api/modules/department'
import { get } from '@/api/client'
import type { ApiResponse } from '@/api/types'
import type { User, Department, Role } from '@/types'
import { formatDateTime } from '@/utils/format'
import { ROLE_LABELS } from '@/utils/constants'

// ===================== 状态 =====================
const loading = ref(false)
const userList = ref<User[]>([])
const departmentTree = ref<Department[]>([])
const roleList = ref<Role[]>([])

// 筛选条件
const searchQuery = ref('')
const filterDepartmentId = ref<number | null>(null)
const filterStatus = ref<string>('')

// 分页
const pagination = reactive({
  page: 1,
  pageSize: 20,
  total: 0,
})

// 弹窗
const dialogVisible = ref(false)
const isEdit = ref(false)
const submitLoading = ref(false)
const formRef = ref<FormInstance>()
const formData = reactive({
  id: 0,
  username: '',
  realName: '',
  password: '',
  email: '',
  phone: '',
  departmentId: undefined as number | undefined,
  roleIds: [] as number[],
  status: 'ACTIVE' as 'ACTIVE' | 'INACTIVE' | 'LOCKED',
})

const formRules: FormRules = {
  username: [
    { required: true, message: '请输入用户名', trigger: 'blur' },
    { min: 3, max: 20, message: '长度在 3 到 20 个字符', trigger: 'blur' },
  ],
  realName: [{ required: true, message: '请输入姓名', trigger: 'blur' }],
  password: [
    { required: !isEdit.value, message: '请输入密码', trigger: 'blur' },
    { min: 6, message: '密码长度至少6位', trigger: 'blur' },
  ],
  email: [
    { required: true, message: '请输入邮箱', trigger: 'blur' },
    { type: 'email', message: '请输入正确的邮箱地址', trigger: 'blur' },
  ],
  departmentId: [{ required: true, message: '请选择部门', trigger: 'change' }],
}

// ===================== 方法 =====================

async function fetchUserList() {
  loading.value = true
  try {
    const params: Record<string, any> = {
      page: pagination.page,
      pageSize: pagination.pageSize,
    }
    if (searchQuery.value) params.search = searchQuery.value
    if (filterDepartmentId.value) params.departmentId = filterDepartmentId.value
    if (filterStatus.value) params.status = filterStatus.value

    const res = await userApi.getUserList(params)
    userList.value = res.data.items
    pagination.total = res.data.total
  } catch (error: any) {
    ElMessage.error(error?.message || '获取用户列表失败')
  } finally {
    loading.value = false
  }
}

async function fetchDepartmentTree() {
  try {
    const res = await departmentApi.getDepartmentTree()
    departmentTree.value = res.data
  } catch (error: any) {
    ElMessage.error(error?.message || '获取部门列表失败')
  }
}

async function fetchRoleList() {
  try {
    const res = await get<Role[]>('/roles/')
    roleList.value = res.data || []
  } catch {
    // 静默处理，使用默认角色列表
  }
}

function getStatusType(status: string) {
  const typeMap: Record<string, string> = {
    ACTIVE: 'success',
    INACTIVE: 'danger',
    LOCKED: 'warning',
  }
  return typeMap[status] || 'info'
}

function getStatusLabel(status: string) {
  const labelMap: Record<string, string> = {
    ACTIVE: '启用',
    INACTIVE: '禁用',
    LOCKED: '锁定',
  }
  return labelMap[status] || status
}

function handleSearch() {
  pagination.page = 1
  fetchUserList()
}

function handleReset() {
  searchQuery.value = ''
  filterDepartmentId.value = null
  filterStatus.value = ''
  pagination.page = 1
  fetchUserList()
}

function handleSizeChange(size: number) {
  pagination.pageSize = size
  fetchUserList()
}

function handlePageChange(page: number) {
  pagination.page = page
  fetchUserList()
}

function handleAdd() {
  isEdit.value = false
  resetForm()
  dialogVisible.value = true
}

function handleEdit(row: User) {
  isEdit.value = true
  resetForm()
  formData.id = row.id
  formData.username = row.username
  formData.realName = row.realName
  formData.email = row.email
  formData.phone = row.phone || ''
  formData.departmentId = row.departmentId
  formData.roleIds = row.roles?.map(r => r.id) || []
  formData.status = row.status
  dialogVisible.value = true
}

function resetForm() {
  formData.id = 0
  formData.username = ''
  formData.realName = ''
  formData.password = ''
  formData.email = ''
  formData.phone = ''
  formData.departmentId = undefined
  formData.roleIds = []
  formData.status = 'ACTIVE'
  formRef.value?.resetFields()
}

async function handleSubmit() {
  const valid = await formRef.value?.validate().catch(() => false)
  if (!valid) return

  submitLoading.value = true
  try {
    if (isEdit.value) {
      await userApi.updateUser(formData.id, {
        realName: formData.realName,
        email: formData.email,
        phone: formData.phone,
        departmentId: formData.departmentId,
        status: formData.status,
      })
      if (formData.roleIds.length > 0) {
        await userApi.assignRoles(formData.id, formData.roleIds)
      }
      ElMessage.success('更新用户成功')
    } else {
      await userApi.createUser({
        username: formData.username,
        realName: formData.realName,
        password: formData.password,
        email: formData.email,
        phone: formData.phone,
        departmentId: formData.departmentId!,
        roleIds: formData.roleIds,
        status: formData.status,
      })
      ElMessage.success('创建用户成功')
    }
    dialogVisible.value = false
    fetchUserList()
  } catch (error: any) {
    ElMessage.error(error?.message || (isEdit.value ? '更新失败' : '创建失败'))
  } finally {
    submitLoading.value = false
  }
}

async function handleResetPassword(row: User) {
  try {
    await ElMessageBox.confirm(
      `确定要重置用户 "${row.realName || row.username}" 的密码吗？`,
      '确认重置密码',
      { type: 'warning' }
    )
    const newPassword = '123456'
    await userApi.resetPassword(row.id, newPassword)
    ElMessage.success(`密码已重置为: ${newPassword}`)
  } catch (error: any) {
    if (error !== 'cancel') {
      ElMessage.error(error?.message || '重置密码失败')
    }
  }
}

async function handleToggleStatus(row: User) {
  const newStatus = row.status === 'ACTIVE' ? 'INACTIVE' : 'ACTIVE'
  const actionText = newStatus === 'ACTIVE' ? '启用' : '禁用'
  try {
    await ElMessageBox.confirm(
      `确定要${actionText}用户 "${row.realName || row.username}" 吗？`,
      `确认${actionText}`,
      { type: 'warning' }
    )
    await userApi.updateUser(row.id, { status: newStatus })
    ElMessage.success(`${actionText}成功`)
    fetchUserList()
  } catch (error: any) {
    if (error !== 'cancel') {
      ElMessage.error(error?.message || '操作失败')
    }
  }
}

// ===================== 生命周期 =====================
onMounted(() => {
  fetchUserList()
  fetchDepartmentTree()
  fetchRoleList()
})
</script>

<style scoped lang="scss">
.page-container {
  padding: 20px;
}

.toolbar {
  display: flex;
  justify-content: space-between;
  align-items: center;
  flex-wrap: wrap;
  gap: 12px;

  .toolbar-left {
    display: flex;
    gap: 12px;
    flex-wrap: wrap;
  }
}

.pagination-container {
  display: flex;
  justify-content: flex-end;
  margin-top: 16px;
}
</style>
